### ISSUE TITLE
When trying to connect; SSH asks for password 

### ISSUE THREAD

**Issue by sxiii** [retog/docker-x11-xpra#5]
This command:
```
ssh -p 2020 user@localhost xclock
```
Does ask for password after accepting certificate. Checked with: my system user; "ubuntu"; "root" and different passwords like "empty", "ubuntu", "root" etc. Doesen't help. I'm on Manjaro 18.1.3.

Thanks.

**Comment by retog** [comment]
Copying your ssh public key with `docker exec` should prevent this. There is no default password, if public key authorization doesn't work you cannot login.
